version: "3.8"
services:
  web:
    build: .
    container_name: charcillaries_web
    environment:
      - ASPNETCORE_ENVIRONMENT=deployment_dev
      - ASPNETCORE_URLS=http://0.0.0.0:80
    networks:
      - nginx_reverse_proxy
      - db_network
 
    volumes:
      - DataProtection-Keys:/root/.aspnet/DataProtection-Keys

volumes:
    DataProtection-Keys:

networks:
  nginx_reverse_proxy:
    external: true
  db_network:
    external: true
