//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SD.LLBLGen.Pro.QuerySpec;
using Charcillaries.Data.HelperClasses;
using SD.LLBLGen.Pro.LinqSupportClasses;
using SD.LLBLGen.Pro.LinqSupportClasses.DTOProjectionHelpers;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Charcillaries.Data.Views.Persistence
{
	///<summary>class to define custom where/orderby clauses to be used in the linq / query spec query projection</summary>
	public partial class FlightRouteListViewProjectionParams
	{
		///<summary>class to define custom where/orderby clauses to be used in the linq / query spec query projection</summary>
		public partial class F_RouteAmenitiesProjectionParams_Clauses
		{
			/// <summary>QuerySpec specific. Appends a new OrderBy clause for the RouteAmenities embedded set.</summary>
			/// <param name="clauseToAdd">the clause to add</param>
			public void AppendQSOrderBy(ISortClause clauseToAdd) => this.QSOrderByClauses.Add(clauseToAdd);
			/// <summary>Linq specific. Appends a new OrderBy clause for the RouteAmenities embedded set.</summary>
			/// <param name="orderByClause">The order by clause to use</param>
			/// <param name="descending">if true, the order by will be descending, otherwise ascending (default)</param>
			/// <typeparam name="TField">The type of the field to sort by</typeparam>
			public void AppendLinqOrderBy<TField>(System.Linq.Expressions.Expression<Func<Charcillaries.Data.EntityClasses.RouteAmenityEntity, TField>> orderByClause, bool descending = false) => this.LinqOrderByClauses.Add(new SD.LLBLGen.Pro.ORMSupportClasses.ValuePair<System.Linq.Expressions.Expression, bool>((System.Linq.Expressions.Expression)orderByClause, descending));
			internal List<SD.LLBLGen.Pro.ORMSupportClasses.ValuePair<System.Linq.Expressions.Expression, bool>> LinqOrderByClauses { get; } = new List<SD.LLBLGen.Pro.ORMSupportClasses.ValuePair<System.Linq.Expressions.Expression, bool>>();
			internal List<ISortClause> QSOrderByClauses { get; set; } = new List<ISortClause>();
			/// <summary>Linq specific. Custom where clause to be used for when the RouteAmenities embedded set is fetched</summary>
			public System.Linq.Expressions.Expression<Func<Charcillaries.Data.EntityClasses.RouteAmenityEntity, bool>> LinqWhereClause { get; set; }
			/// <summary>QuerySpec specific. Custom where clause to be used for when the RouteAmenities embedded set is fetched</summary>
			public IPredicate QSWhereClause { get; set; }
		}

		/// <summary>Projection parameters to configure where / orderby clauses for the nested member 'RouteAmenities'</summary>
		public F_RouteAmenitiesProjectionParams_Clauses RouteAmenitiesProjectionParams { get; } = new F_RouteAmenitiesProjectionParams_Clauses();
	}

	/// <summary>Static class for (extension) methods for fetching and projecting instances of Charcillaries.Data.Views.DtoClasses.FlightRouteListView from the entity model.</summary>
	public static partial class FlightRouteListViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<Charcillaries.Data.EntityClasses.FlightRouteEntity, Charcillaries.Data.Views.DtoClasses.FlightRouteListView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<Charcillaries.Data.EntityClasses.FlightRouteEntity, Charcillaries.Data.Views.DtoClasses.FlightRouteListView> _compiledProjector = CreateProjectionFunc().Compile();
		/// <summary>Linq specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToFlightRouteListView(System.Linq.IQueryable{Charcillaries.Data.EntityClasses.FlightRouteEntity})"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="CreateProjectionFunc"/></param>
		/// <remarks>Linq specific</remarks>
		static partial void GetAdjustmentsForProjectToFlightRouteListView(ref System.Linq.Expressions.Expression<Func<Charcillaries.Data.EntityClasses.FlightRouteEntity, Charcillaries.Data.Views.DtoClasses.FlightRouteListView>> projectionAdjustments);
		/// <summary>QuerySpec specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToFlightRouteListView(EntityQuery{Charcillaries.Data.EntityClasses.FlightRouteEntity}, Charcillaries.Data.FactoryClasses.QueryFactory)"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="ProjectToFlightRouteListView(EntityQuery{Charcillaries.Data.EntityClasses.FlightRouteEntity}, Charcillaries.Data.FactoryClasses.QueryFactory)"/></param>
		/// <remarks>QuerySpec specific</remarks>
		static partial void GetAdjustmentsForProjectToFlightRouteListViewQs(ref System.Linq.Expressions.Expression<Func<Charcillaries.Data.Views.DtoClasses.FlightRouteListView>> projectionAdjustments);
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static FlightRouteListViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to Charcillaries.Data.Views.DtoClasses.FlightRouteListView which instances are projected from the results of the specified baseQuery, which returns Charcillaries.Data.EntityClasses.FlightRouteEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve Charcillaries.Data.Views.DtoClasses.FlightRouteListView instances</returns>
		public static IQueryable<Charcillaries.Data.Views.DtoClasses.FlightRouteListView> ProjectToFlightRouteListView(this IQueryable<Charcillaries.Data.EntityClasses.FlightRouteEntity> baseQuery) => ProjectToFlightRouteListView(baseQuery, null);
		/// <summary>Extension method which produces a projection to Charcillaries.Data.Views.DtoClasses.FlightRouteListView which instances are projected from the results of the specified baseQuery, which returns Charcillaries.Data.EntityClasses.FlightRouteEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <param name="projectionParams">The optional projection parameters with optional where/orderby clauses for nested sets in the projection</param>
		/// <returns>IQueryable to retrieve Charcillaries.Data.Views.DtoClasses.FlightRouteListView instances</returns>
		public static IQueryable<Charcillaries.Data.Views.DtoClasses.FlightRouteListView> ProjectToFlightRouteListView(this IQueryable<Charcillaries.Data.EntityClasses.FlightRouteEntity> baseQuery, FlightRouteListViewProjectionParams projectionParams)
		{
			if(projectionParams == null)
			{
				return baseQuery.Select(_projectorExpression);
			}
			return baseQuery.Select(CreateProjectionFunc(projectionParams));
		}

		/// <summary>Extension method which produces a projection to Charcillaries.Data.Views.DtoClasses.FlightRouteListView which instances are projected from the results of the specified baseQuery using QuerySpec, which returns Charcillaries.Data.EntityClasses.FlightRouteEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <param name="qf">The query factory used to create baseQuery.</param>
		/// <returns>DynamicQuery to retrieve Charcillaries.Data.Views.DtoClasses.FlightRouteListView instances</returns>
		public static DynamicQuery<Charcillaries.Data.Views.DtoClasses.FlightRouteListView> ProjectToFlightRouteListView(this EntityQuery<Charcillaries.Data.EntityClasses.FlightRouteEntity> baseQuery, Charcillaries.Data.FactoryClasses.QueryFactory qf) => ProjectToFlightRouteListView(baseQuery, qf, null);
		/// <summary>Extension method which produces a projection to Charcillaries.Data.Views.DtoClasses.FlightRouteListView which instances are projected from the results of the specified baseQuery using QuerySpec, which returns Charcillaries.Data.EntityClasses.FlightRouteEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <param name="qf">The query factory used to create baseQuery.</param>
		/// <param name="projectionParams">The optional projection parameters with optional where/orderby clauses for nested sets in the projection</param>
		/// <returns>DynamicQuery to retrieve Charcillaries.Data.Views.DtoClasses.FlightRouteListView instances</returns>
		public static DynamicQuery<Charcillaries.Data.Views.DtoClasses.FlightRouteListView> ProjectToFlightRouteListView(this EntityQuery<Charcillaries.Data.EntityClasses.FlightRouteEntity> baseQuery, Charcillaries.Data.FactoryClasses.QueryFactory qf, FlightRouteListViewProjectionParams projectionParams=null)
		{
			System.Linq.Expressions.Expression<Func<Charcillaries.Data.Views.DtoClasses.FlightRouteListView>> projectionAdjustments = null;
			GetAdjustmentsForProjectToFlightRouteListViewQs(ref projectionAdjustments);
			return qf.Create()
				.From(baseQuery.Select(Projection.Full).As("__BQ"))
				.Select(LinqUtils.MergeProjectionAdjustmentsIntoProjection(() => new Charcillaries.Data.Views.DtoClasses.FlightRouteListView()
				{
					ArrivalAirport = FlightRouteFields.ArrivalAirport.Source("__BQ").ToValue<System.String>(),
					DepartureAirport = FlightRouteFields.DepartureAirport.Source("__BQ").ToValue<System.String>(),
					Id = FlightRouteFields.Id.Source("__BQ").ToValue<System.Int32>(),
					RouteAmenities = (List<Charcillaries.Data.Views.DtoClasses.FlightRouteListViewTypes.RouteAmenity>)qf.RouteAmenity.TargetAs("__L1_0")
						.CorrelatedOver(FlightRouteFields.Id.Source("__BQ").Equal(RouteAmenityFields.FlightRouteId.Source("__L1_0")))
						.From(QueryTarget
							.InnerJoin(qf.Amenity.As("__L1_1")).On(RouteAmenityFields.AmenityId.Source("__L1_0").Equal(AmenityFields.Id.Source("__L1_1"))))
						.Where(projectionParams==null ? null : GeneralUtils.SetAliasOnPredicate(projectionParams.RouteAmenitiesProjectionParams.QSWhereClause, "__L1_0"))
						.OrderBy(projectionParams==null ? null : GeneralUtils.SetAliasOnSortClauses(projectionParams.RouteAmenitiesProjectionParams.QSOrderByClauses, "__L1_0"))
						.Select(() => new Charcillaries.Data.Views.DtoClasses.FlightRouteListViewTypes.RouteAmenity()
						{
							Amenity = new Charcillaries.Data.Views.DtoClasses.FlightRouteListViewTypes.RouteAmenityTypes.Amenity()
								{
									Name = AmenityFields.Name.Source("__L1_1").ToValue<System.String>(),
									ObjectStatus = AmenityFields.ObjectStatus.Source("__L1_1").ToValue<System.Int32>(),
								},
							AmenityId = RouteAmenityFields.AmenityId.Source("__L1_0").ToValue<System.Int32>(),
							FlightRouteId = RouteAmenityFields.FlightRouteId.Source("__L1_0").ToValue<System.Int32>(),
							Id = RouteAmenityFields.Id.Source("__L1_0").ToValue<System.Int32>(),
							ObjectStatus = RouteAmenityFields.ObjectStatus.As("ObjectStatus1").Source("__L1_0").ToValue<System.Int32>(),
							Price = RouteAmenityFields.Price.Source("__L1_0").ToValue<System.Single>(),
							Quantity = RouteAmenityFields.Quantity.Source("__L1_0").ToValue<Nullable<System.Int32>>(),
						}).ToResultset(),
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegionQS_FlightRouteListView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
				}, projectionAdjustments, false));
		}

		/// <summary>Extension method which produces a projection to Charcillaries.Data.Views.DtoClasses.FlightRouteListView which instances are projected from the Charcillaries.Data.EntityClasses.FlightRouteEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>Charcillaries.Data.EntityClasses.FlightRouteEntity instance created from the specified entity instance</returns>
		public static Charcillaries.Data.Views.DtoClasses.FlightRouteListView ProjectToFlightRouteListView(this Charcillaries.Data.EntityClasses.FlightRouteEntity entity)
		{
			return _compiledProjector(entity);
		}

		private static System.Linq.Expressions.Expression<Func<Charcillaries.Data.EntityClasses.FlightRouteEntity, Charcillaries.Data.Views.DtoClasses.FlightRouteListView>> CreateProjectionFunc(FlightRouteListViewProjectionParams projectionParams=null)
		{
			System.Linq.Expressions.Expression<Func<Charcillaries.Data.EntityClasses.FlightRouteEntity, Charcillaries.Data.Views.DtoClasses.FlightRouteListView>> mainProjection = p__0 => new Charcillaries.Data.Views.DtoClasses.FlightRouteListView()
			{
				ArrivalAirport = p__0.ArrivalAirport,
				DepartureAirport = p__0.DepartureAirport,
				Id = p__0.Id,
				RouteAmenities = p__0.RouteAmenities.AsQueryable().OptionalWhere(projectionParams.RouteAmenitiesProjectionParams.LinqWhereClause).OptionalOrderBy(projectionParams.RouteAmenitiesProjectionParams.LinqOrderByClauses).Select(p__1 => new Charcillaries.Data.Views.DtoClasses.FlightRouteListViewTypes.RouteAmenity()
				{
					Amenity = new Charcillaries.Data.Views.DtoClasses.FlightRouteListViewTypes.RouteAmenityTypes.Amenity()
					{
						Name = p__1.Amenity.Name,
						ObjectStatus = p__1.Amenity.ObjectStatus,
					},
					AmenityId = p__1.AmenityId,
					FlightRouteId = p__1.FlightRouteId,
					Id = p__1.Id,
					ObjectStatus = p__1.ObjectStatus,
					Price = p__1.Price,
					Quantity = p__1.Quantity,
				}).ToList(),
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_FlightRouteListView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
			System.Linq.Expressions.Expression<Func<Charcillaries.Data.EntityClasses.FlightRouteEntity, Charcillaries.Data.Views.DtoClasses.FlightRouteListView>> projectionAdjustments = null;
			GetAdjustmentsForProjectToFlightRouteListView(ref projectionAdjustments);
			return LinqUtils.MergeProjectionAdjustmentsIntoProjection(mainProjection, projectionAdjustments, true);
		}
	}
}


