//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SD.LLBLGen.Pro.QuerySpec;
using Charcillaries.Data.HelperClasses;
using SD.LLBLGen.Pro.LinqSupportClasses;
using SD.LLBLGen.Pro.LinqSupportClasses.DTOProjectionHelpers;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Charcillaries.Data.Views.Persistence
{

	/// <summary>Static class for (extension) methods for fetching and projecting instances of Charcillaries.Data.Views.DtoClasses.PassengersDetailsView from the entity model.</summary>
	public static partial class PassengersDetailsViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<Charcillaries.Data.EntityClasses.PassengerEntity, Charcillaries.Data.Views.DtoClasses.PassengersDetailsView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<Charcillaries.Data.EntityClasses.PassengerEntity, Charcillaries.Data.Views.DtoClasses.PassengersDetailsView> _compiledProjector = CreateProjectionFunc().Compile();
		/// <summary>Linq specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToPassengersDetailsView(System.Linq.IQueryable{Charcillaries.Data.EntityClasses.PassengerEntity})"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="CreateProjectionFunc"/></param>
		/// <remarks>Linq specific</remarks>
		static partial void GetAdjustmentsForProjectToPassengersDetailsView(ref System.Linq.Expressions.Expression<Func<Charcillaries.Data.EntityClasses.PassengerEntity, Charcillaries.Data.Views.DtoClasses.PassengersDetailsView>> projectionAdjustments);
		/// <summary>QuerySpec specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToPassengersDetailsView(EntityQuery{Charcillaries.Data.EntityClasses.PassengerEntity}, Charcillaries.Data.FactoryClasses.QueryFactory)"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="ProjectToPassengersDetailsView(EntityQuery{Charcillaries.Data.EntityClasses.PassengerEntity}, Charcillaries.Data.FactoryClasses.QueryFactory)"/></param>
		/// <remarks>QuerySpec specific</remarks>
		static partial void GetAdjustmentsForProjectToPassengersDetailsViewQs(ref System.Linq.Expressions.Expression<Func<Charcillaries.Data.Views.DtoClasses.PassengersDetailsView>> projectionAdjustments);
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static PassengersDetailsViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to Charcillaries.Data.Views.DtoClasses.PassengersDetailsView which instances are projected from the results of the specified baseQuery, which returns Charcillaries.Data.EntityClasses.PassengerEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve Charcillaries.Data.Views.DtoClasses.PassengersDetailsView instances</returns>
		public static IQueryable<Charcillaries.Data.Views.DtoClasses.PassengersDetailsView> ProjectToPassengersDetailsView(this IQueryable<Charcillaries.Data.EntityClasses.PassengerEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}

		/// <summary>Extension method which produces a projection to Charcillaries.Data.Views.DtoClasses.PassengersDetailsView which instances are projected from the results of the specified baseQuery using QuerySpec, which returns Charcillaries.Data.EntityClasses.PassengerEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <param name="qf">The query factory used to create baseQuery.</param>
		/// <returns>DynamicQuery to retrieve Charcillaries.Data.Views.DtoClasses.PassengersDetailsView instances</returns>
		public static DynamicQuery<Charcillaries.Data.Views.DtoClasses.PassengersDetailsView> ProjectToPassengersDetailsView(this EntityQuery<Charcillaries.Data.EntityClasses.PassengerEntity> baseQuery, Charcillaries.Data.FactoryClasses.QueryFactory qf)
		{
			System.Linq.Expressions.Expression<Func<Charcillaries.Data.Views.DtoClasses.PassengersDetailsView>> projectionAdjustments = null;
			GetAdjustmentsForProjectToPassengersDetailsViewQs(ref projectionAdjustments);
			return qf.Create()
				.From(baseQuery.Select(Projection.Full).As("__BQ")
					.InnerJoin(qf.Person.As("__L0_0")).On(PassengerFields.PersonId.Source("__BQ").Equal(PersonFields.Id.Source("__L0_0"))))
				.Select(LinqUtils.MergeProjectionAdjustmentsIntoProjection(() => new Charcillaries.Data.Views.DtoClasses.PassengersDetailsView()
				{
					Id = PassengerFields.Id.Source("__BQ").ToValue<System.Int32>(),
					Person = new Charcillaries.Data.Views.DtoClasses.PassengersDetailsViewTypes.Person()
						{
							Email = PersonFields.Email.Source("__L0_0").ToValue<System.String>(),
							FirstName = PersonFields.FirstName.Source("__L0_0").ToValue<System.String>(),
							Id = PersonFields.Id.As("Id1").Source("__L0_0").ToValue<System.Int32>(),
							LastName = PersonFields.LastName.Source("__L0_0").ToValue<System.String>(),
							PassportNumber = PersonFields.PassportNumber.Source("__L0_0").ToValue<System.String>(),
							PhoneNumber = PersonFields.PhoneNumber.Source("__L0_0").ToValue<System.String>(),
						},
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegionQS_PassengersDetailsView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
				}, projectionAdjustments, false));
		}

		/// <summary>Extension method which produces a projection to Charcillaries.Data.Views.DtoClasses.PassengersDetailsView which instances are projected from the Charcillaries.Data.EntityClasses.PassengerEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>Charcillaries.Data.EntityClasses.PassengerEntity instance created from the specified entity instance</returns>
		public static Charcillaries.Data.Views.DtoClasses.PassengersDetailsView ProjectToPassengersDetailsView(this Charcillaries.Data.EntityClasses.PassengerEntity entity)
		{
			return _compiledProjector(entity);
		}

		private static System.Linq.Expressions.Expression<Func<Charcillaries.Data.EntityClasses.PassengerEntity, Charcillaries.Data.Views.DtoClasses.PassengersDetailsView>> CreateProjectionFunc()
		{
			System.Linq.Expressions.Expression<Func<Charcillaries.Data.EntityClasses.PassengerEntity, Charcillaries.Data.Views.DtoClasses.PassengersDetailsView>> mainProjection = p__0 => new Charcillaries.Data.Views.DtoClasses.PassengersDetailsView()
			{
				Id = p__0.Id,
				Person = new Charcillaries.Data.Views.DtoClasses.PassengersDetailsViewTypes.Person()
				{
					Email = p__0.Person.Email,
					FirstName = p__0.Person.FirstName,
					Id = p__0.Person.Id,
					LastName = p__0.Person.LastName,
					PassportNumber = p__0.Person.PassportNumber,
					PhoneNumber = p__0.Person.PhoneNumber,
				},
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_PassengersDetailsView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
			System.Linq.Expressions.Expression<Func<Charcillaries.Data.EntityClasses.PassengerEntity, Charcillaries.Data.Views.DtoClasses.PassengersDetailsView>> projectionAdjustments = null;
			GetAdjustmentsForProjectToPassengersDetailsView(ref projectionAdjustments);
			return LinqUtils.MergeProjectionAdjustmentsIntoProjection(mainProjection, projectionAdjustments, true);
		}
	}
}


