//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Charcillaries.Data.Views.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'AmenityFeedback'.</summary>
	[Serializable]
	[DataContract]
	public partial class AmenityFeedbackDetailsView
	{
		/// <summary>Gets or sets the Amenity field. </summary>
		[DataMember]
		public AmenityFeedbackDetailsViewTypes.Amenity Amenity { get; set; }
		/// <summary>Gets or sets the AmenityId field. Derived from Entity Model Field 'AmenityFeedback.AmenityId (FK)'</summary>
		[DataMember]
		public System.Int32 AmenityId { get; set; }
		/// <summary>Gets or sets the Comment field. Derived from Entity Model Field 'AmenityFeedback.Comment'</summary>
		[DataMember]
		public System.String Comment { get; set; }
		/// <summary>Gets or sets the DateCreated field. Derived from Entity Model Field 'AmenityFeedback.DateCreated'</summary>
		[DataMember]
		public System.DateTime DateCreated { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'AmenityFeedback.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the Passenger field. </summary>
		[DataMember]
		public AmenityFeedbackDetailsViewTypes.Passenger Passenger { get; set; }
		/// <summary>Gets or sets the PassengerId field. Derived from Entity Model Field 'AmenityFeedback.PassengerId (FK)'</summary>
		[DataMember]
		public System.Int32 PassengerId { get; set; }
		/// <summary>Gets or sets the Rating field. Derived from Entity Model Field 'AmenityFeedback.Rating'</summary>
		[DataMember]
		public Nullable<System.Int32> Rating { get; set; }
	}

	namespace AmenityFeedbackDetailsViewTypes
	{
		/// <summary> DTO class which is derived from the entity 'Amenity (Amenity)'.</summary>
		[Serializable]
		[DataContract]
		public partial class Amenity
		{
			/// <summary>Gets or sets the AirlineId field. Derived from Entity Model Field 'Amenity.AirlineId (FK)'</summary>
			[DataMember]
			public System.Int32 AirlineId { get; set; }
			/// <summary>Gets or sets the Description field. Derived from Entity Model Field 'Amenity.Description'</summary>
			[DataMember]
			public System.String Description { get; set; }
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Amenity.Id'</summary>
			[DataMember]
			public System.Int32 Id { get; set; }
			/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Amenity.Name'</summary>
			[DataMember]
			public System.String Name { get; set; }
		}

		/// <summary> DTO class which is derived from the entity 'Passenger (Passenger)'.</summary>
		[Serializable]
		[DataContract]
		public partial class Passenger
		{
			/// <summary>Gets or sets the Flight field. </summary>
			[DataMember]
			public PassengerTypes.Flight Flight { get; set; }
			/// <summary>Gets or sets the Person field. </summary>
			[DataMember]
			public PassengerTypes.Person Person { get; set; }
		}

		namespace PassengerTypes
		{
			/// <summary> DTO class which is derived from the entity 'Flight (Passenger.Flight)'.</summary>
			[Serializable]
			[DataContract]
			public partial class Flight
			{
				/// <summary>Gets or sets the ArrivalDate field. Derived from Entity Model Field 'Flight.ArrivalDate'</summary>
				[DataMember]
				public System.DateTime ArrivalDate { get; set; }
				/// <summary>Gets or sets the DepartureDate field. Derived from Entity Model Field 'Flight.DepartureDate'</summary>
				[DataMember]
				public System.DateTime DepartureDate { get; set; }
				/// <summary>Gets or sets the FlightNumber field. Derived from Entity Model Field 'Flight.FlightNumber'</summary>
				[DataMember]
				public System.String FlightNumber { get; set; }
				/// <summary>Gets or sets the FlightRouteId field. Derived from Entity Model Field 'Flight.FlightRouteId (FK)'</summary>
				[DataMember]
				public System.Int32 FlightRouteId { get; set; }
				/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Flight.Id'</summary>
				[DataMember]
				public System.Int32 Id { get; set; }
				/// <summary>Gets or sets the NumberOfSeats field. Derived from Entity Model Field 'Flight.NumberOfSeats'</summary>
				[DataMember]
				public System.Int32 NumberOfSeats { get; set; }
				/// <summary>Gets or sets the ObjectStatus field. Derived from Entity Model Field 'Flight.ObjectStatus'</summary>
				[DataMember]
				public System.Int32 ObjectStatus { get; set; }
				/// <summary>Gets or sets the TourOperatorId field. Derived from Entity Model Field 'Flight.TourOperatorId (FK)'</summary>
				[DataMember]
				public System.Int32 TourOperatorId { get; set; }
			}

			/// <summary> DTO class which is derived from the entity 'Person (Passenger.Person)'.</summary>
			[Serializable]
			[DataContract]
			public partial class Person
			{
				/// <summary>Gets or sets the FirstName field. Derived from Entity Model Field 'Person.FirstName'</summary>
				[DataMember]
				public System.String FirstName { get; set; }
				/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Person.Id'</summary>
				[DataMember]
				public System.Int32 Id { get; set; }
				/// <summary>Gets or sets the LastName field. Derived from Entity Model Field 'Person.LastName'</summary>
				[DataMember]
				public System.String LastName { get; set; }
				/// <summary>Gets or sets the ObjectStatus field. Derived from Entity Model Field 'Person.ObjectStatus'</summary>
				[DataMember]
				public System.Int32 ObjectStatus { get; set; }
			}
		}
	}

}




