//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Charcillaries.Data.Views.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'AmenityFeedback'.</summary>
	[Serializable]
	[DataContract]
	public partial class AmenityFeedbackMinimalView
	{
		/// <summary>Gets or sets the AmenityId field. Derived from Entity Model Field 'AmenityFeedback.AmenityId (FK)'</summary>
		[DataMember]
		public System.Int32 AmenityId { get; set; }
		/// <summary>Gets or sets the Comment field. Derived from Entity Model Field 'AmenityFeedback.Comment'</summary>
		[DataMember]
		public System.String Comment { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'AmenityFeedback.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the Rating field. Derived from Entity Model Field 'AmenityFeedback.Rating'</summary>
		[DataMember]
		public Nullable<System.Int32> Rating { get; set; }
	}

}




