//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Charcillaries.Data.Views.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Flight'.</summary>
	[Serializable]
	[DataContract]
	public partial class FlightDetailsView
	{
		/// <summary>Gets or sets the ArrivalDate field. Derived from Entity Model Field 'Flight.ArrivalDate'</summary>
		[DataMember]
		public System.DateTime ArrivalDate { get; set; }
		/// <summary>Gets or sets the DepartureDate field. Derived from Entity Model Field 'Flight.DepartureDate'</summary>
		[DataMember]
		public System.DateTime DepartureDate { get; set; }
		/// <summary>Gets or sets the FlightNumber field. Derived from Entity Model Field 'Flight.FlightNumber'</summary>
		[DataMember]
		public System.String FlightNumber { get; set; }
		/// <summary>Gets or sets the FlightRoute field. </summary>
		[DataMember]
		public FlightDetailsViewTypes.FlightRoute FlightRoute { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Flight.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the NumberOfSeats field. Derived from Entity Model Field 'Flight.NumberOfSeats'</summary>
		[DataMember]
		public System.Int32 NumberOfSeats { get; set; }
		/// <summary>Gets or sets the TourOperator field. </summary>
		[DataMember]
		public FlightDetailsViewTypes.TourOperator TourOperator { get; set; }
		/// <summary>Gets or sets the TourOperatorId field. Derived from Entity Model Field 'Flight.TourOperatorId (FK)'</summary>
		[DataMember]
		public System.Int32 TourOperatorId { get; set; }
	}

	namespace FlightDetailsViewTypes
	{
		/// <summary> DTO class which is derived from the entity 'FlightRoute (FlightRoute)'.</summary>
		[Serializable]
		[DataContract]
		public partial class FlightRoute
		{
			/// <summary>Gets or sets the AirlineId field. Derived from Entity Model Field 'FlightRoute.AirlineId (FK)'</summary>
			[DataMember]
			public System.Int32 AirlineId { get; set; }
			/// <summary>Gets or sets the ArrivalAirport field. Derived from Entity Model Field 'FlightRoute.ArrivalAirport'</summary>
			[DataMember]
			public System.String ArrivalAirport { get; set; }
			/// <summary>Gets or sets the DepartureAirport field. Derived from Entity Model Field 'FlightRoute.DepartureAirport'</summary>
			[DataMember]
			public System.String DepartureAirport { get; set; }
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'FlightRoute.Id'</summary>
			[DataMember]
			public System.Int32 Id { get; set; }
		}

		/// <summary> DTO class which is derived from the entity 'TourOperator (TourOperator)'.</summary>
		[Serializable]
		[DataContract]
		public partial class TourOperator
		{
			/// <summary>Gets or sets the ContactInfo field. Derived from Entity Model Field 'TourOperator.ContactInfo'</summary>
			[DataMember]
			public System.String ContactInfo { get; set; }
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'TourOperator.Id'</summary>
			[DataMember]
			public System.Int32 Id { get; set; }
			/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'TourOperator.Name'</summary>
			[DataMember]
			public System.String Name { get; set; }
		}
	}

}




