//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Charcillaries.Data.Views.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Passenger'.</summary>
	[Serializable]
	[DataContract]
	public partial class PassengerListView
	{
		/// <summary>Gets or sets the Flight field. </summary>
		[DataMember]
		public PassengerListViewTypes.Flight Flight { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Passenger.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the Person field. </summary>
		[DataMember]
		public PassengerListViewTypes.Person Person { get; set; }
	}

	namespace PassengerListViewTypes
	{
		/// <summary> DTO class which is derived from the entity 'Flight (Flight)'.</summary>
		[Serializable]
		[DataContract]
		public partial class Flight
		{
			/// <summary>Gets or sets the FlightNumber field. Derived from Entity Model Field 'Flight.FlightNumber'</summary>
			[DataMember]
			public System.String FlightNumber { get; set; }
		}

		/// <summary> DTO class which is derived from the entity 'Person (Person)'.</summary>
		[Serializable]
		[DataContract]
		public partial class Person
		{
			/// <summary>Gets or sets the Email field. Derived from Entity Model Field 'Person.Email'</summary>
			[DataMember]
			public System.String Email { get; set; }
			/// <summary>Gets or sets the FirstName field. Derived from Entity Model Field 'Person.FirstName'</summary>
			[DataMember]
			public System.String FirstName { get; set; }
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Person.Id'</summary>
			[DataMember]
			public System.Int32 Id { get; set; }
			/// <summary>Gets or sets the LastName field. Derived from Entity Model Field 'Person.LastName'</summary>
			[DataMember]
			public System.String LastName { get; set; }
			/// <summary>Gets or sets the PhoneNumber field. Derived from Entity Model Field 'Person.PhoneNumber'</summary>
			[DataMember]
			public System.String PhoneNumber { get; set; }
		}
	}

}




