//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Charcillaries.Data.Views.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'RouteFlightFeedback'.</summary>
	[Serializable]
	[DataContract]
	public partial class RouteFlightFeedbackMinimalView
	{
		/// <summary>Gets or sets the Comment field. Derived from Entity Model Field 'RouteFlightFeedback.Comment'</summary>
		[DataMember]
		public System.String Comment { get; set; }
		/// <summary>Gets or sets the Rating field. Derived from Entity Model Field 'RouteFlightFeedback.Rating'</summary>
		[DataMember]
		public Nullable<System.Int32> Rating { get; set; }
	}

}




