//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Charcillaries.Data.Views.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'TourOperator'.</summary>
	[Serializable]
	[DataContract]
	public partial class TourOperatorDetailsView
	{
		/// <summary>Gets or sets the ContactInfo field. Derived from Entity Model Field 'TourOperator.ContactInfo'</summary>
		[DataMember]
		public System.String ContactInfo { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'TourOperator.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'TourOperator.Name'</summary>
		[DataMember]
		public System.String Name { get; set; }
	}

}




