//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace Charcillaries.Data
{


	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>Airline</summary>
		AirlineEntity,
		///<summary>Amenity</summary>
		AmenityEntity,
		///<summary>AmenityFeedback</summary>
		AmenityFeedbackEntity,
		///<summary>Flight</summary>
		FlightEntity,
		///<summary>FlightRoute</summary>
		FlightRouteEntity,
		///<summary>Passenger</summary>
		PassengerEntity,
		///<summary>PassengerAmenitySelection</summary>
		PassengerAmenitySelectionEntity,
		///<summary>Person</summary>
		PersonEntity,
		///<summary>Role</summary>
		RoleEntity,
		///<summary>RouteAmenity</summary>
		RouteAmenityEntity,
		///<summary>RouteFlightFeedback</summary>
		RouteFlightFeedbackEntity,
		///<summary>TourOperator</summary>
		TourOperatorEntity,
		///<summary>TourOperatorAirline</summary>
		TourOperatorAirlineEntity,
		///<summary>User</summary>
		UserEntity
	}



	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END

}

