//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Charcillaries.Data.HelperClasses
{
	/// <summary>Field Creation Class for entity AirlineEntity</summary>
	public partial class AirlineFields
	{
		/// <summary>Creates a new AirlineEntity.ContactInfo field instance</summary>
		public static EntityField2 ContactInfo { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AirlineFieldIndex.ContactInfo); }}
		/// <summary>Creates a new AirlineEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AirlineFieldIndex.Email); }}
		/// <summary>Creates a new AirlineEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AirlineFieldIndex.Id); }}
		/// <summary>Creates a new AirlineEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AirlineFieldIndex.Name); }}
		/// <summary>Creates a new AirlineEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AirlineFieldIndex.ObjectStatus); }}
	}

	/// <summary>Field Creation Class for entity AmenityEntity</summary>
	public partial class AmenityFields
	{
		/// <summary>Creates a new AmenityEntity.AirlineId field instance</summary>
		public static EntityField2 AirlineId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.AirlineId); }}
		/// <summary>Creates a new AmenityEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.Description); }}
		/// <summary>Creates a new AmenityEntity.Icon field instance</summary>
		public static EntityField2 Icon { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.Icon); }}
		/// <summary>Creates a new AmenityEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.Id); }}
		/// <summary>Creates a new AmenityEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.Name); }}
		/// <summary>Creates a new AmenityEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.ObjectStatus); }}
	}

	/// <summary>Field Creation Class for entity AmenityFeedbackEntity</summary>
	public partial class AmenityFeedbackFields
	{
		/// <summary>Creates a new AmenityFeedbackEntity.AmenityId field instance</summary>
		public static EntityField2 AmenityId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFeedbackFieldIndex.AmenityId); }}
		/// <summary>Creates a new AmenityFeedbackEntity.Comment field instance</summary>
		public static EntityField2 Comment { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFeedbackFieldIndex.Comment); }}
		/// <summary>Creates a new AmenityFeedbackEntity.DateCreated field instance</summary>
		public static EntityField2 DateCreated { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFeedbackFieldIndex.DateCreated); }}
		/// <summary>Creates a new AmenityFeedbackEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFeedbackFieldIndex.Id); }}
		/// <summary>Creates a new AmenityFeedbackEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFeedbackFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new AmenityFeedbackEntity.PassengerId field instance</summary>
		public static EntityField2 PassengerId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFeedbackFieldIndex.PassengerId); }}
		/// <summary>Creates a new AmenityFeedbackEntity.Rating field instance</summary>
		public static EntityField2 Rating { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFeedbackFieldIndex.Rating); }}
	}

	/// <summary>Field Creation Class for entity FlightEntity</summary>
	public partial class FlightFields
	{
		/// <summary>Creates a new FlightEntity.ArrivalDate field instance</summary>
		public static EntityField2 ArrivalDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(FlightFieldIndex.ArrivalDate); }}
		/// <summary>Creates a new FlightEntity.DepartureDate field instance</summary>
		public static EntityField2 DepartureDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(FlightFieldIndex.DepartureDate); }}
		/// <summary>Creates a new FlightEntity.FlightNumber field instance</summary>
		public static EntityField2 FlightNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(FlightFieldIndex.FlightNumber); }}
		/// <summary>Creates a new FlightEntity.FlightRouteId field instance</summary>
		public static EntityField2 FlightRouteId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(FlightFieldIndex.FlightRouteId); }}
		/// <summary>Creates a new FlightEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(FlightFieldIndex.Id); }}
		/// <summary>Creates a new FlightEntity.NumberOfSeats field instance</summary>
		public static EntityField2 NumberOfSeats { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(FlightFieldIndex.NumberOfSeats); }}
		/// <summary>Creates a new FlightEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(FlightFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new FlightEntity.TourOperatorId field instance</summary>
		public static EntityField2 TourOperatorId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(FlightFieldIndex.TourOperatorId); }}
	}

	/// <summary>Field Creation Class for entity FlightRouteEntity</summary>
	public partial class FlightRouteFields
	{
		/// <summary>Creates a new FlightRouteEntity.AirlineId field instance</summary>
		public static EntityField2 AirlineId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(FlightRouteFieldIndex.AirlineId); }}
		/// <summary>Creates a new FlightRouteEntity.ArrivalAirport field instance</summary>
		public static EntityField2 ArrivalAirport { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(FlightRouteFieldIndex.ArrivalAirport); }}
		/// <summary>Creates a new FlightRouteEntity.DepartureAirport field instance</summary>
		public static EntityField2 DepartureAirport { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(FlightRouteFieldIndex.DepartureAirport); }}
		/// <summary>Creates a new FlightRouteEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(FlightRouteFieldIndex.Id); }}
		/// <summary>Creates a new FlightRouteEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(FlightRouteFieldIndex.ObjectStatus); }}
	}

	/// <summary>Field Creation Class for entity PassengerEntity</summary>
	public partial class PassengerFields
	{
		/// <summary>Creates a new PassengerEntity.FlightId field instance</summary>
		public static EntityField2 FlightId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PassengerFieldIndex.FlightId); }}
		/// <summary>Creates a new PassengerEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PassengerFieldIndex.Id); }}
		/// <summary>Creates a new PassengerEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PassengerFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new PassengerEntity.PaymentAmount field instance</summary>
		public static EntityField2 PaymentAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PassengerFieldIndex.PaymentAmount); }}
		/// <summary>Creates a new PassengerEntity.PaymentConfirmation field instance</summary>
		public static EntityField2 PaymentConfirmation { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PassengerFieldIndex.PaymentConfirmation); }}
		/// <summary>Creates a new PassengerEntity.PaymentConfirmationDate field instance</summary>
		public static EntityField2 PaymentConfirmationDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PassengerFieldIndex.PaymentConfirmationDate); }}
		/// <summary>Creates a new PassengerEntity.PersonId field instance</summary>
		public static EntityField2 PersonId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PassengerFieldIndex.PersonId); }}
	}

	/// <summary>Field Creation Class for entity PassengerAmenitySelectionEntity</summary>
	public partial class PassengerAmenitySelectionFields
	{
		/// <summary>Creates a new PassengerAmenitySelectionEntity.Confirmed field instance</summary>
		public static EntityField2 Confirmed { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PassengerAmenitySelectionFieldIndex.Confirmed); }}
		/// <summary>Creates a new PassengerAmenitySelectionEntity.Customization field instance</summary>
		public static EntityField2 Customization { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PassengerAmenitySelectionFieldIndex.Customization); }}
		/// <summary>Creates a new PassengerAmenitySelectionEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PassengerAmenitySelectionFieldIndex.Id); }}
		/// <summary>Creates a new PassengerAmenitySelectionEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PassengerAmenitySelectionFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new PassengerAmenitySelectionEntity.PassengerId field instance</summary>
		public static EntityField2 PassengerId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PassengerAmenitySelectionFieldIndex.PassengerId); }}
		/// <summary>Creates a new PassengerAmenitySelectionEntity.Quantity field instance</summary>
		public static EntityField2 Quantity { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PassengerAmenitySelectionFieldIndex.Quantity); }}
		/// <summary>Creates a new PassengerAmenitySelectionEntity.RouteAmenityId field instance</summary>
		public static EntityField2 RouteAmenityId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PassengerAmenitySelectionFieldIndex.RouteAmenityId); }}
	}

	/// <summary>Field Creation Class for entity PersonEntity</summary>
	public partial class PersonFields
	{
		/// <summary>Creates a new PersonEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.Email); }}
		/// <summary>Creates a new PersonEntity.FirstName field instance</summary>
		public static EntityField2 FirstName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.FirstName); }}
		/// <summary>Creates a new PersonEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.Id); }}
		/// <summary>Creates a new PersonEntity.LastName field instance</summary>
		public static EntityField2 LastName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.LastName); }}
		/// <summary>Creates a new PersonEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new PersonEntity.PassportNumber field instance</summary>
		public static EntityField2 PassportNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.PassportNumber); }}
		/// <summary>Creates a new PersonEntity.PhoneNumber field instance</summary>
		public static EntityField2 PhoneNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.PhoneNumber); }}
	}

	/// <summary>Field Creation Class for entity RoleEntity</summary>
	public partial class RoleFields
	{
		/// <summary>Creates a new RoleEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RoleFieldIndex.Id); }}
		/// <summary>Creates a new RoleEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RoleFieldIndex.Name); }}
		/// <summary>Creates a new RoleEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RoleFieldIndex.ObjectStatus); }}
	}

	/// <summary>Field Creation Class for entity RouteAmenityEntity</summary>
	public partial class RouteAmenityFields
	{
		/// <summary>Creates a new RouteAmenityEntity.AmenityId field instance</summary>
		public static EntityField2 AmenityId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RouteAmenityFieldIndex.AmenityId); }}
		/// <summary>Creates a new RouteAmenityEntity.FlightRouteId field instance</summary>
		public static EntityField2 FlightRouteId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RouteAmenityFieldIndex.FlightRouteId); }}
		/// <summary>Creates a new RouteAmenityEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RouteAmenityFieldIndex.Id); }}
		/// <summary>Creates a new RouteAmenityEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RouteAmenityFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new RouteAmenityEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RouteAmenityFieldIndex.Price); }}
		/// <summary>Creates a new RouteAmenityEntity.Quantity field instance</summary>
		public static EntityField2 Quantity { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RouteAmenityFieldIndex.Quantity); }}
	}

	/// <summary>Field Creation Class for entity RouteFlightFeedbackEntity</summary>
	public partial class RouteFlightFeedbackFields
	{
		/// <summary>Creates a new RouteFlightFeedbackEntity.Comment field instance</summary>
		public static EntityField2 Comment { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RouteFlightFeedbackFieldIndex.Comment); }}
		/// <summary>Creates a new RouteFlightFeedbackEntity.DateCreated field instance</summary>
		public static EntityField2 DateCreated { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RouteFlightFeedbackFieldIndex.DateCreated); }}
		/// <summary>Creates a new RouteFlightFeedbackEntity.FlightId field instance</summary>
		public static EntityField2 FlightId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RouteFlightFeedbackFieldIndex.FlightId); }}
		/// <summary>Creates a new RouteFlightFeedbackEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RouteFlightFeedbackFieldIndex.Id); }}
		/// <summary>Creates a new RouteFlightFeedbackEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RouteFlightFeedbackFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new RouteFlightFeedbackEntity.PassengerId field instance</summary>
		public static EntityField2 PassengerId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RouteFlightFeedbackFieldIndex.PassengerId); }}
		/// <summary>Creates a new RouteFlightFeedbackEntity.Rating field instance</summary>
		public static EntityField2 Rating { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RouteFlightFeedbackFieldIndex.Rating); }}
	}

	/// <summary>Field Creation Class for entity TourOperatorEntity</summary>
	public partial class TourOperatorFields
	{
		/// <summary>Creates a new TourOperatorEntity.ContactInfo field instance</summary>
		public static EntityField2 ContactInfo { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TourOperatorFieldIndex.ContactInfo); }}
		/// <summary>Creates a new TourOperatorEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TourOperatorFieldIndex.Id); }}
		/// <summary>Creates a new TourOperatorEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TourOperatorFieldIndex.Name); }}
		/// <summary>Creates a new TourOperatorEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TourOperatorFieldIndex.ObjectStatus); }}
	}

	/// <summary>Field Creation Class for entity TourOperatorAirlineEntity</summary>
	public partial class TourOperatorAirlineFields
	{
		/// <summary>Creates a new TourOperatorAirlineEntity.AirlineId field instance</summary>
		public static EntityField2 AirlineId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TourOperatorAirlineFieldIndex.AirlineId); }}
		/// <summary>Creates a new TourOperatorAirlineEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TourOperatorAirlineFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new TourOperatorAirlineEntity.TourOperatorId field instance</summary>
		public static EntityField2 TourOperatorId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TourOperatorAirlineFieldIndex.TourOperatorId); }}
	}

	/// <summary>Field Creation Class for entity UserEntity</summary>
	public partial class UserFields
	{
		/// <summary>Creates a new UserEntity.AirlineId field instance</summary>
		public static EntityField2 AirlineId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.AirlineId); }}
		/// <summary>Creates a new UserEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Id); }}
		/// <summary>Creates a new UserEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new UserEntity.Password field instance</summary>
		public static EntityField2 Password { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Password); }}
		/// <summary>Creates a new UserEntity.PersonId field instance</summary>
		public static EntityField2 PersonId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.PersonId); }}
		/// <summary>Creates a new UserEntity.ResetToken field instance</summary>
		public static EntityField2 ResetToken { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.ResetToken); }}
		/// <summary>Creates a new UserEntity.ResetTokenExpiration field instance</summary>
		public static EntityField2 ResetTokenExpiration { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.ResetTokenExpiration); }}
		/// <summary>Creates a new UserEntity.RoleId field instance</summary>
		public static EntityField2 RoleId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.RoleId); }}
		/// <summary>Creates a new UserEntity.TourOperatorId field instance</summary>
		public static EntityField2 TourOperatorId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.TourOperatorId); }}
	}
	

}